### ISSUE TITLE
can not find `ValaConfig.cmake vala-config.cmake` error on Ubuntu 16.04

### ISSUE THREAD

**Issue by kensully** [bitseater/weather#12]
First of all, thanks for your work. I am running Ubuntu 16.04, I tried to build it but I got the error below:

         CMake Error at CMakeLists.txt:33 (find_package):
           By not providing "FindVala.cmake" in CMAKE_MODULE_PATH this project has
           asked CMake to find a package configuration file provided by "Vala", but
           CMake did not find one.

           Could not find a package configuration file provided by "Vala" with any of
           the following names:

             ValaConfig.cmake
             vala-config.cmake

           Add the installation prefix of "Vala" to CMAKE_PREFIX_PATH or set
           "Vala_DIR" to a directory containing one of the above files.  If "Vala"
           provides a separate development package or SDK, be sure it has been
           installed.

I think it requires `cmake-elementary` and `elementary-sdk` but they are not included in Ubuntu repos.

**Comment by bitseater** [comment]
Thanks for download, try and report the issue, @kensully . Your can add the elementary-os repos from `ppa:elementary-os/stable` . I'll change README.md in the next commit.

**Comment by bitseater** [comment]
Hello @kensully . I have added cmake files and support for Debian / Ubuntu. Thanks for your help.
