### ISSUE TITLE
Move city map to popover

### ISSUE THREAD

**Issue by cassidyjames** [bitseater/weather#15]
I like that I can now distinguish between cities of the same name with a map; great work! I do think it's a little awkward that it opens in a whole new window, though, and just kind of hangs around forever. Instead, would it be possible to put it into a popover?

That way you could also add a `.suggested-action` button to the primary position in the popover, and use it as a confirmation (instead of requiring a double-click in the list

```
-^--------------------------------
|                                |
|                                |
|              (map)             |
|                                |
|                                |
|--------------------------------|
|                       [Select] |
----------------------------------
```

**Comment by bitseater** [comment]
Hello @cassidyjames . I have think about _revealers_, but yours sound a good idea. Saved.

**Comment by bitseater** [comment]
Resolved with commit 41
