### ISSUE TITLE
Redesign "new location" screen

### ISSUE THREAD

**Issue by cassidyjames** [bitseater/weather#17]
This would be a pretty substantial redesign for this screen, but I think it would help focus on the information that matters in a more visually pleasing way.

```
 -----------------------------------------------
| x    [ 🔍 Search for a location        ]    ⚙ |
|-----------------------------------------------|
| -------                                       |
| | map |  Denver, Colorado US         [Select] |
| -------                                       |
|                                               |
| -------                                       |
| | map |  Denver, Victoria AU         [Select] |
| -------                                       |
|                                               |
| -------                                       |
| | map |  Denver, Pennsylvania US     [Select] |
| -------                                       |
|                                               |
| -------                                       |
| | map |  Denver, Iowa US             [Select] |
| -------                                       |
 -----------------------------------------------
``````

**Comment by cassidyjames** [comment]
Then clicking on the map preview could show the popover described in #15

**Comment by cassidyjames** [comment]
To describe the ASCII sketch in prose,

- Put the location search entry in the headerbar
- Show a small/medium-sized map preview next to each location, zoomed to a level that makes it relatively easy to confirm the location visually
- Clicking the map shows the popover with a much larger map
- Add a Select button in each row to make choosing a city a single-click operation
- Add the state/region to the location name (if possible, like Colorado, Victoria, etc. in the mockup)
- Format the location name more naturally (City, Country)
- Remove the column headers since the data should be self-evident
- Remove the OpenWM ID (I don't see how this is useful to a human)

**Comment by bitseater** [comment]
Actually, i'm working in Geoclue & OWM integration, you know. With it , we can modify this screen. Thanks for your comments and suggestions.

**Comment by bitseater** [comment]
I have the screen and the search engine with geocode-glib . Take a look at:

[searchcity.vala](
https://gist.github.com/bitseater/22489cf0f3d28c32509969b6b3ad10a7)

Working now on maps inside popovers ...

**Comment by bitseater** [comment]
Solved with commit 41
