### ISSUE TITLE
Consider changing name

### ISSUE THREAD

**Issue by cassidyjames** [bitseater/weather#18]
"Weather" is super generic, and doesn't really explain what the app does. According to our [publishing guidelines](https://github.com/elementary/houston/wiki/Before-You-Publish#naming), you should avoid overly-generic names.

Something like "Forecast" might be more accurate and descriptive. Note: you can rename the user-facing .desktop and AppData strings without changing the RDNN (as you can't change the RDNN in AppCenter).

**Comment by bitseater** [comment]
Hi @cassidyjames , @bil-elmoussaoui , @danrabbit  : 

I would like to ask your opinion about the change of name. I have in mind two options : **FORECAST**, as @cassidyjames  suggested, or **METEO**, as an abbreviation for meteorology. Please, feel free to tell me other names.

On the other hand, I would like to know your expert opinion on the process of change of name. A simple change in the .desktop and .appdata strings, or perhaps it would be better to open a new repository with, for example, the name and version _Forecast 1.0_ or _Meteo 1.0_ . 

How does it affect to the process of creating a flathub package, @bil-elmoussaoui ?
How does it affect to the actual application in AppCenter, @cassidyjames and @danrabbit?

I'm waiting for your comments. Thanks in advance.

**Comment by bil-elmoussaoui** [comment]
Changing the application name in the desktop file and the appdata file won't affect the flatpak build on flathub. As soon as you don't change the RDNN. There's no way to change/update the RDNN on flathub neither (at the moment, there's some work on that).

**Comment by bitseater** [comment]
Hi friends. Finally I change desktop, appdata and in-app "name" strings to ... METEO.

All references to FORECAST word are in english, meanwhile METEO has meaning in other languages. You can take a look at [duckduckgo]( https://duckduckgo.com/?q=meteo) . It is also the name of several meteorological services of various countries all over the world. 

So, my choose is METEO. Thanks for the suggestions and the ideas about the way to change it. Close this issue,
