### ISSUE TITLE
could you make a flatpak for weather?

### ISSUE THREAD

**Issue by altntowin** [bitseater/weather#25]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for weather?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by corebots** [comment]
A flatpak would be nice indeed!

**Comment by bil-elmoussaoui** [comment]
Here you go https://github.com/flathub/flathub/pull/260

**Comment by bitseater** [comment]
Close this, cause @bil-elmoussaoui and me are working on it. See #36 for more info.

**Comment by bitseater** [comment]
Hi @altntowin @corebots : 
https://flathub.org/repo/appstream/com.github.bitseater.weather.flatpakref
Greetings.

**Comment by altntowin** [comment]
Thanks :)
