### ISSUE TITLE
Add indicator support

### ISSUE THREAD

**Issue by khurshid-alam** [bitseater/weather#27]
A indicator based on libapppindicator would be nice. When clicking on indicator it should open the main app.

Something like this.
![indicator-weather2](https://user-images.githubusercontent.com/1333217/35770420-e7a5bc28-0940-11e8-9b90-0af455cb6110.png)

**Comment by bitseater** [comment]
It just developed and it comes with others features in 0.5 version, available in the next 2 weeks. You can take a look to [ROADMAP](https://github.com/bitseater/weather/wiki) or perhaps you want to see this video: https://youtu.be/gsEAK9Puua4

**Comment by khurshid-alam** [comment]
Oh. My bad..I didn't know it was already on the roadmap! Thanks.

**Comment by bitseater** [comment]
Just works.
