### ISSUE TITLE
Use local cache

### ISSUE THREAD

**Issue by khurshid-alam** [bitseater/weather#28]
It would be nice if the app can use a local cache, i.e. weather data stored in a local file. It could be a simple database or even a simple json file.

Thanks.

**Comment by bitseater** [comment]
Hi @khurshid-alam . Are you talking about saving each query to local database? or some of them? OpenWeatherMap API have an option to query historical data, but it's to expensive for normal users. The Term of Use of this API warns about keeping information historical to offer to users. I try to find another solution, preferably for free.

**Comment by khurshid-alam** [comment]
No, not the entire weather history, some of them. I am talking about only current weather data...(and not all the data type but the most important one like temp, humidity, etc). Every-time the app updates the weather it should save/overwrite the data to a database.

**Comment by bitseater** [comment]
Good news @khurshid-alam . OWM accept to save the current query to local cache, in order to prevent numerous queries from same IP. I'm going to add a note to ROADMAP to include it as soon as possible.

**Comment by khurshid-alam** [comment]
Awesome!

**Comment by bitseater** [comment]
I have added a simple screen with current weather data , showing a cache file with them. You can copy and paste these data, or you can save the cache file to another folder. In next release, I will develop this feature more deeply.

**Comment by bitseater** [comment]
@khurshid-alam , a simple view of data to copy and paste, to the next release. More features in the future. I close this issue.

**Comment by khurshid-alam** [comment]
@bitseater In case of offline will it use that cache data? I think it describes the problem in another issue.

**Comment by bitseater** [comment]
Yes @khurshid-alam it will use the cache data in the next releases. Now i must fix some issues as soon as possible , for people who use Flatpak, so i need to commit a new release in these days.
