### ISSUE TITLE
UK Settings

### ISSUE THREAD

**Issue by daveg208** [bitseater/weather#29]
For reference, in the UK we tend to use Degrees C with MPH windspeed. 
The settings allow for Degrees C with M/s windspeed or Degrees F with MPH, neither of which is useful.

Regards

Dave

**Comment by bitseater** [comment]
Take note to add configuration. Thanks

**Comment by bitseater** [comment]
Hi there, @daveg208 . I'm developing this feature, but i need to know others units. Please, fill free to correct me:
Temperature : ºC
Wind speed: mph
Pressure: hpa (hectopascals) ?
Precipitation : inph (inch per hour) ?
I'm waiting for your comments. Thanks.

**Comment by bitseater** [comment]
According to official [Meteo Service from UK Goverment](https://www.metoffice.gov.uk/about-us/units-of-measurement-faq) i assume the units marked above. New feature added and developed. Closing this issue.
