### ISSUE TITLE
Use a transparent screenshot for indicator

### ISSUE THREAD

**Issue by danrabbit** [bitseater/weather#33]
I've marked the 0.5.2 release as needs fixing for the following reason:

Please use a transparent screenshot to show your indicator. You can do this with the "Grab the current window" option in screenshot tool and opening the applications menu to make sure the panel is the focused window. I would recommend using a white wallpaper so that your icons adapt and are visible in AppCenter

Also please only show your indicator in additional to the default indicators. In the current screenshot it is unclear which indicator that your app is responsible for since there are many non-default indicators

**Comment by cassidyjames** [comment]
I also think for any indicators, the screenshots should include the indicator menu being open.

**Comment by bitseater** [comment]
HI @danrabbit @cassidyjames , do you mean something like this :

[https://github.com/bitseater/weather/raw/master/data/screens/screenshot_4.png](https://github.com/bitseater/weather/raw/master/data/screens/screenshot_4.png)  ?

**Comment by danrabbit** [comment]
That's much better :)

**Comment by bitseater** [comment]
Gracias Dani / @danrabbit . Making a new release to send to dashboard. Thanks.
