### ISSUE TITLE
Indicator startup

### ISSUE THREAD

**Issue by giovannicaligaris** [bitseater/weather#34]
Is there a way to open the indicator without executing the app?

I would like to have the indicator launched at startup.

**Comment by bitseater** [comment]
Hi @giovannicaligaris . Thanks for your suggestion. I'm working on Weather to add this feature, with many others. Added to Roadmap.

**Comment by bitseater** [comment]
Hi @giovannicaligaris . Now we have minimized on start-up option added to preferences. It will be included in the next release, or (if you don’t want to wait a few days) you can manually clone and build this repository.  Thanks for the suggestion.

**Comment by giovannicaligaris** [comment]
Great! I will check it out in a few days when is available from the AppCenter.
