### ISSUE TITLE
Publish on Flathub Please!

### ISSUE THREAD

**Issue by alex285** [bitseater/weather#36]
and also change name https://github.com/bitseater/weather/issues/18 :)

**Comment by bil-elmoussaoui** [comment]
See https://github.com/flathub/flathub/pull/260

**Comment by bitseater** [comment]
Working on it now. Thanks again @bil-elmoussaoui

**Comment by bitseater** [comment]
Some errors here when i try to flatpak-build:
```
checking for headers required to compile python extensions... found
checking for APPINDICATOR_PYTHON... no
configure: error: Package requirements (
					pygtk-2.0 >= 2.14.0
					gtk+-2.0 >= 2.18
					pygobject-2.0 >= 0.22
                  ) were not met:

No package 'pygtk-2.0' found
No package 'pygobject-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables APPINDICATOR_PYTHON_CFLAGS
and APPINDICATOR_PYTHON_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
Error: module libappindicator: El proceso hijo terminó con el código 1.
```
Any ideas ?

**Comment by bil-elmoussaoui** [comment]
Have you checked my PR ? You need the two patches that I have added. libappindicator by default try to build python gobject-introspection, and there's no build flag to disable that. A patch is required to disable that

**Comment by bitseater** [comment]
Ok, only add no-python.patch.

**Comment by bil-elmoussaoui** [comment]
Yeah, the other patch will be removed once there's a new release! I kept it for now, just to see if the build will be successful on all the architectures supported by Flathub workers

**Comment by bitseater** [comment]
Hi @bil-elmoussaoui . Same errors with two patch files. Searching for a solution i find this:

[org.telegram.desktop/libappindicator-disable-python-bindings.patch](https://github.com/flathub/org.telegram.desktop/blob/master/libappindicator-disable-python-bindings.patch)

Now i can build and run it.  Do you think is necessary all this patch file to avoid the errors above?

Sorry for my question, but I'm new to Flatpak.

**Comment by bil-elmoussaoui** [comment]
@bitseater The build works correctly in my case. The patch you're proposing removes a lot of stuff that shouldn't be required at all... 
Anyway, we will see what the flathub builders reports back. Can you publish a new release with all those recent fixes (meson and appdata one)? 
Thanks!

**Comment by bitseater** [comment]
With the two files (meson-fix.patch and no-python.patch) from flathub/flathub#260 ?

**Comment by bil-elmoussaoui** [comment]
Nop, there's no need for the no-python at all. The meson-fix patch is already applied on the master branch. What I meant, is a new release of the application here, on your repository. So I can update and fix the json file of flatpak package. And test it with the latest fixes

**Comment by bitseater** [comment]
Hi @bil-elmoussaoui , i just have created 0.5.4 release. Thanks for your work.

**Comment by bil-elmoussaoui** [comment]
All we have to do is to wait for the maintainers to either approve it and create a repository for it. Or to ask for some modifications

**Comment by bil-elmoussaoui** [comment]
Already there https://github.com/flathub/com.github.bitseater.weather

**Comment by bitseater** [comment]
Thanks @bil-elmoussaoui . If i understood, now i have to change json file every time a push a new release in the new flathub repository (flathub/com.github.bitseater.weather). Isn't it?

**Comment by bil-elmoussaoui** [comment]
Yes, with the new dependencies or just update the release tarball and the sha256 checksum :)

**Comment by bitseater** [comment]
Thanks again. It has been a great help on your part.

**Comment by bitseater** [comment]
Hi @bil-elmoussaoui : 
[https://flathub.org/repo/appstream/com.github.bitseater.weather.flatpakref](https://flathub.org/repo/appstream/com.github.bitseater.weather.flatpakref)

Thanks.
