### ISSUE TITLE
Feature Request: Launch minimised

### ISSUE THREAD

**Issue by jos-henson** [bitseater/weather#42]
Hi there,

I really love the app and the rate at which you are actively developing it is really impressive.

One small feature request I was wondering if it would be possible to implement is to have the app launch minimised (e.g. just with the tray icon) by default, as I would love to have it launch at system startup without the window showing.

Just a very minor thing and probably not something that would be a priority of yours, but I thought maybe it didn't hurt to at least ask in case I'm not the only one that would like to see this!

Will definitely throw a couple of dollars/euros/pounds your way if you are able to make this happen (either via the app store or patreon etc if you are setup there instead).

Thanks again for all your great work on this app, it is killing gnome-weather! ;-)

**Comment by bitseater** [comment]
Thank you very mych, @jos-henson . This features is just developed. You can see the next features in [RoadMap](https://github.com/bitseater/weather/wiki) . I hope v0.6 will be release in the next two weeks. 

You will can select between to start up with o without indicator, and to start up minimized to system tray or not. All options are available in preferences window.

Thanks again for your comments.

You can support the elementary OS project, if you don't actually do, at [Patreon](https://www.patreon.com/elementary). In the future, when the application will be more stable and developed, you'll can contributed via AppCenter if you want.

**Comment by jos-henson** [comment]
Hi there,

Thank you so much for the quick response, apologies that I didn't notice this in the roadmap already!!

Quick question: Will this also prevent the application from showing in the Dock? Or is that not really possible due to the limitations of how the Dock/elementary os actually work?

Thanks again for your answer/work on this app, I already support elementary via patreon and they definitely deserve every penny! (and I will definitely support your app via the AppCenter when it is possible!) :-)

**Comment by bitseater** [comment]
Hi and yes, this prevent to show in Plank dock. Only show in dock when focus the main window of the application (data & maps). When you click on minimized, it minimized to dock. If you click on close, it minimized to indicator in wingpanel, and disappear from dock . To quit the app, you must go to indicator and choose "Quit".  If you choose not to use indicator, when you run the app, always show in dock. When you click on minimized , it minimized to dock, and when you click on close, the app close and quit.

I hope i explain the UI response. Thanks.

**Comment by jos-henson** [comment]
Thanks and apologies again for asking a question before trying the app properly myself!!

But yes, that is all perfectly clear and it works great!
