### ISSUE TITLE
Reload/update weather

### ISSUE THREAD

**Issue by giovannicaligaris** [bitseater/weather#44]
Sometimes when I lose internet connection at home (the worst!), the weather will either get stuck at the last digit that it was recorded or it will go to 0 degrees or sometimes it won't show anything at all.

The only way to refresh this is by closing the weather app and reopening. 

This is not a big deal but it would be nice to have an option to update the weather similar to the app "my-weather-indicator".

**Comment by bitseater** [comment]
OpenWeatherMap API has a limited numbers of queries per apikey, so i removed the update button from version 0.2 to prevent apikey blocks. In the next version 0.6 it will have a cache file with the last weather conditions, to prevent this issue. I added in the last days a note to [ROADMAP](https://github.com/bitseater/weather/wiki). Thanks for your comment.

**Comment by bitseater** [comment]
Developed. Now you will have an update button if you have your own API key.
