### ISSUE TITLE
Support language PT-BR

### ISSUE THREAD

**Issue by LeandroStanger** [bitseater/weather#46]

**Comment by bitseater** [comment]
Olá @LeandroStanger , obrigado pelo seu comentário. Existe uma tradução para o portugues no link [pt.po](https://github.com/bitseater/weather/blob/master/po/pt.po)

Se quiser alterar alguma linha, me façam saber, se não a farei como valida para pt_BR. Obrigado.

**Comment by LeandroStanger** [comment]
![captura de tela 4de 2018-02-15 11-19-34](https://user-images.githubusercontent.com/26097419/36258804-3ff6350a-1243-11e8-98fc-f8fed6d134cf.png)
![captura de tela de 2018-02-15 411-19-08](https://user-images.githubusercontent.com/26097419/36258805-402d01b6-1243-11e8-858a-254b941af88f.png)

**Comment by bitseater** [comment]
A new pt_BR language file is just translated. I will commit it to new release in this weekend. Thanks for your comment.

**Comment by bitseater** [comment]
Added new pt_BR.po file.
