### ISSUE TITLE
Flatpak build doesnt start

### ISSUE THREAD

**Issue by alex285** [bitseater/weather#47]
i installed Meteo
```
flatpak install --user flathub com.github.bitseater.weather
```

but when i try to run it
```
flatpak run com.github.bitseater.weather
```
nothing is happening! i can see the process running, but there is not app, and nothing on output. @bil-elmoussaoui 

Ubuntu 18.04/ Flatpak 0.11.1

**Comment by bitseater** [comment]
Hi @alex285. It seems something about flatpak and wayland support. I'm going to prepare a environment with them and Ubuntu 18.04 to test the app and debug it.

**Comment by alex285** [comment]
@bitseater ah sorry i didnt mention before, but i use Xorg
also, at some point it opened a blank window. same as the other guy said on G+

**Comment by bil-elmoussaoui** [comment]
It does work on my laptop without any issue at all...

**Comment by alex285** [comment]
@bitseater i run it on Arch Linux, and i think i figured out the issue. when the app starts, it starts hidden, and i had to use the indicator to show it

on Ubuntu thought the indicator wasnt visible, or i didnt notice it. on elementary Juno, i think the indicator isn't event working

**Comment by bitseater** [comment]
Yes @alex285 . All it's about lib-indicator package. It isn't support in Flatpak, cause it hasn't supported in Fedora/Gnome, so ... it need a patch to work, but you cannot initialize the app minimized, so i must to change some default setting. I am working in a new release (appcenter, ppa y flatpak package) to commit this weekend.

**Comment by bitseater** [comment]
@alex285,  i try it in ubuntu 18.04 with ubuntu appindicator extension and it works. In Juno 'alpha' don't work, i tried it last afternoon. So i'm planning to eliminate libindicator (no supported by Flatpak, nor Gnome nor Fedora) and make a release for Flatpak without libappindicator and other release for elementary-os / wingpanel support.

**Comment by alex285** [comment]
@bitseater just to understand. you will remove the indicator, so when you close the app from {x}
1. the app will shutdown
2. or the app will still run on background? and there will be a quit button to exit?

**Comment by bitseater** [comment]
@alex285 I've got the indicator work in Juno "alpha" with ayatana indicators. Now i need to make work on Gnome, to Ubuntu 18.04-Gnome-Fedora-Flatpak..... I will try again.

**Comment by bitseater** [comment]
New gresource file with start no minimized and no indicator, to avoid flatpak issue.
