### ISSUE TITLE
Error with Portuguese Language

### ISSUE THREAD

**Issue by MrMarukesu** [bitseater/weather#48]
I'm using the appcenter version (0.5.3) and seem that a error making the weather using the Pt mixed with En. like in the image
![screenshot from 2018-02-15 11 07 20](https://user-images.githubusercontent.com/21296444/36258250-29a8b96e-1241-11e8-9497-de89cfb90747.png)

**Comment by bitseater** [comment]
Some string are missing in the portuguese language file (pt.po). I just translated them and commit to new release in this weekend. Thanks for your comment.

**Comment by bitseater** [comment]
New pt_PT.po file.

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-02-21 18-22-34](https://user-images.githubusercontent.com/26097419/36506057-38d51cf0-1734-11e8-8edd-5cb1f4c1ab7b.png)

**Comment by bitseater** [comment]
I just publish a new release (0.6.0) 2 hours ago. Is it all Ok now? If you see some mistake, just put here the correct translation. Thanks.
