### ISSUE TITLE
wind speed map disappears in Dark Sky mode in  flatpak 

### ISSUE THREAD

**Issue by kensully** [bitseater/weather#49]
Thank you for developing this application. I am running Ubuntu 16.04, I installed it via flathub. When I launch it, it is running well except wind speed map disappears in Dark Sky mode. It loads the map but it disappears immediately leaving window tab blank.

**Comment by bitseater** [comment]
Hi @kensully , thanks for your comment. It's seems something about flatpak and wayland. I'm making some tests to debug the flatpak package.

**Comment by kensully** [comment]
Hi @bitseater , thank you for responding. I am using Xorg, not wayland. All the other maps work except `wind speed map`

**Comment by bitseater** [comment]
It's seems some problem in the Dark Sky side. Can you try again ??

**Comment by kensully** [comment]
I tried it again, `Temperature`, `Clouds`, `Precipitation`, `Pressure` tabs loads well. but when I click the final `Wind Speed` tab,  its content disappears as soon as it loads the wind map. It doesn't seem to be rendering issue, wrong or missing loop check?

**Comment by kensully** [comment]
I don't know if it's related, I get 
      * (com.github.bitseater.weather:2): CRITICAL **: string_substring: assertion '(_tmp17_ + _tmp18_) <= _tmp19_' failed

error from terminal

**Comment by bitseater** [comment]
Ok Thanks @kensully . It's related. Preparing a patch to solve it. Thanks again.

**Comment by bitseater** [comment]
Related with #28 . Possible solution: Parse JSON data and show cache data when no connect.

**Comment by bitseater** [comment]
Fix issue with commit [41c4c57](https://github.com/bitseater/weather/commit/41c4c572968ee325199edd7a50bab7f23cf5e0fa)
