### ISSUE TITLE
Can't distinguish between cities of the same name

### ISSUE THREAD

**Issue by cassidyjames** [bitseater/weather#5]
It looks like there are multiple Denver, USAs (i.e. in different states). It makes it hard to distinguish which is the one I want; perhaps showing the state name (if available through the API) or showing them on a map would help users narrow it down?

**Comment by bitseater** [comment]
Hi Cassidy. This is a limitation of the OWM API that I just discovered (I live in a country that puts a tagline to the cities with the same name, like _Talavera La Real_ vs _Talavera de la Reina_). The only way to distinguish the cities is through their coordinates. I'm going to try to implement a map overlay on mouse over TreeView.

**Comment by bitseater** [comment]
Improved new vision map with Clutter and Champlain to select between city with the same name.
