### ISSUE TITLE
Clicking "Maps" before entering API key breaks the app

### ISSUE THREAD

**Issue by Shnatsel** [bitseater/weather#52]
Steps to reproduce:

1. Install Weather for the first time
1. Click "Maps" before entering OpenWeatherMap API key
1. Switch back to "Data"

This results in the following application state with no clear recovery route:

![screenshot from 2018-02-23 00-54-54](https://user-images.githubusercontent.com/291257/36566413-7b44baf4-1834-11e8-8623-d4c6cf39694d.png)

The Maps/Data switcher should be insensitive until initial setup is completed.

**Comment by bitseater** [comment]
Thanks for your post @Shnatsel . Are you using flatpak package or appcenter installation?

**Comment by bitseater** [comment]
Confirmed in both builds (flatpak & appcenter).

**Comment by bitseater** [comment]
Fixed with [this commit](https://github.com/bitseater/weather/commit/05724fc4892ef4a1843ea5543e778b25a87fa9a3)
