### ISSUE TITLE
API key prompt is never explained

### ISSUE THREAD

**Issue by Shnatsel** [bitseater/weather#53]
When a new user opens the app, there is no explanation of why they're prompted with an API key and what the consequences of each choice would be:

![screenshot from 2018-02-23 00-59-15](https://user-images.githubusercontent.com/291257/36566516-c9184642-1834-11e8-9c03-dcbdf0fa6fd4.png)

It should be explained what entering a custom API key does, or why is it needed.

**Comment by bitseater** [comment]
Adding "help section" to roadmap. Thanks for the submission.

**Comment by bitseater** [comment]
I just implemented a new Dialog with information about built-in key. Included in 0.7 release.
