### ISSUE TITLE
Refresh icon colour

### ISSUE THREAD

**Issue by cicindel** [bitseater/weather#55]
Hi, thanks a lot for the update/refresh button, i wanted to suggest that but didn't get around to do it. Just one detail, the colour of its icon looks different (lighter) than the rest of the icons (at least in dark theme; in light theme it looks gray, as inactive).
![image](https://user-images.githubusercontent.com/19331850/36798406-d70137da-1caa-11e8-898f-2adbbf7a0da9.png)
![image](https://user-images.githubusercontent.com/19331850/36798490-1432439c-1cab-11e8-87c7-61b8e1273466.png)

**Comment by bitseater** [comment]
Hi @cicindel , it's seems you're using the built-in API key. With this key, the update button is disabled, to avoid all people calling with same key at same time and blocking it. 
If you want to enable the update button, you must register for a own API key at [OpenWeatherMap](https://home.openweathermap.org/users/sign_up)

**Comment by cicindel** [comment]
Aha I see, thanks :)
