### ISSUE TITLE
Feature: Please add some of the weather data into the indicator icon.

### ISSUE THREAD

**Issue by OpnSrcConstruction** [bitseater/weather#57]
Here are the basic details that I'm wishing for:
humidity
precipitation
temperature
pressure
Wind direction/speed
sunset/sunrise
clouds %

This is the one feature, that would keep me from using my-weather-indicator on a non-elementary distro. It's too bad Elementary has to such sticklers for only their indicators!

**Comment by bitseater** [comment]
Hi @OpnSrcConstruction . Thanks you for the comments. I have added to Roadmap this feature that i had in my mind too. Perhaps 0.8 release.

**Comment by bitseater** [comment]
@OpnSrcConstruction good news. Working in your proposal feature. Added to 0.7 milestone.

**Comment by bitseater** [comment]
Solves with commit [89e3322](https://github.com/bitseater/weather/commit/89e3322153bfe055cf5dc9c0708d198e726dede6).
