### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by BeatriceFendt** [bitseater/weather#58]
Hi there,
can you please have a look at the screenshot? I think that explains this issue best.
I am using [Linux Mint 18.3 Sylvia](https://linuxmint.com/) and [Flatpak](https://flatpak.org/).
Do not hesitate to ask any questions you may have.

![ue](https://user-images.githubusercontent.com/34834134/37165887-fc719c2c-22fd-11e8-9bd9-c583601f331d.png)

Thank you so much! 👍

**Comment by bitseater** [comment]
Hi @BeatriceFendt . It seems a bug with no-latin characters and flatpak. I have fixed few weeks ago for russian & other languages. Let me take a look. That is Deutsch, isn't it? Perhaps " überwiegend bewölkt"?

**Comment by bitseater** [comment]
It is a problem with the upper-case letters (Ü - ü). It seems that flatpak don't recognize. I remove first upper-case. Fixed.

**Comment by BeatriceFendt** [comment]
Yes, it is Deutsch. _Überwiegend bewölkt_ is correct.
Thanks for the fast fix.
Just drop a line if you need help with the German translation. We could translate the other parts too.

**Comment by bitseater** [comment]
That would be perfect. Take a look to "po" folder to master pot file. Have you translate any application?  You can use a fork to do it.
