### ISSUE TITLE
Use GeoClue2 to get location

### ISSUE THREAD

**Issue by danrabbit** [bitseater/weather#61]
Juno will have location services built in to privacy, but in order for this to work we need apps to use the system location API and not try to do manual location detection.

You can see an example of fetching location with geoclue here: https://github.com/danrabbit/nimbus/blob/master/src/MainWindow.vala#L159

You probably need this VAPI: https://github.com/danrabbit/nimbus/blob/master/vapi/libgeoclue-2.0.vapi

Sorry, I know it isn't super convenient to use right now. I'll work with the team on getting proper docs up and if we can get that VAPI shipped with the system

**Comment by bitseater** [comment]
OK @danrabbit.  i have already tested with geoclue. I'll work on it.

**Comment by danrabbit** [comment]
Docs are up :) https://valadoc.org/libgeoclue-2.0/GClue.html

**Comment by bitseater** [comment]
Thanks Dani @danrabbit , this solves some doubts.

**Comment by bitseater** [comment]
Fixed by [815a7a9](https://github.com/bitseater/weather/commit/815a7a9976b2089d014a5c8f076f46ae9e90c947)
