### ISSUE TITLE
ubuntu installation problem 

### ISSUE THREAD

**Issue by Sadi58** [bitseater/weather#80]
Under **LinuxMint 18.3 Cinnamon**, when I enter the command `sudo add-apt-repository ppa:bitseater/ppa` and `sudo apt update` and then 
`sudo apt install com.github.bitseater.weather` I get this error: **Unable to locate package com.github.bitseater.weather**
It's correctly listed in LinuxMint's **Software Sources**, but it's not listed in Synaptic Package Manager's **Origin** section.
No other PPA has such a problem.

**Comment by Sadi58** [comment]
I thank you! Looks great having installed via release pages.
Maybe you might like to add this info to ReadMe.

**Comment by bitseater** [comment]
Fixed with [fbffd92](https://github.com/bitseater/weather/commit/fbffd92bbdf512b2353428da442aa11a2be8bae3)
