### ISSUE TITLE
[Feature Request] multi-city weather

### ISSUE THREAD

**Issue by Sadi58** [bitseater/weather#82]
If it is possible/realistic I would like to suggest enabling users to run more than one instance so as to keep an eye on the weather conditions simultaneously in say two or three locations.
At the moment if you start a new instance it seems to merely supersede the previous one.
If this new feature becomes possible it might also be a good idea to add the location name in the systray menu as well (e.g. at the top) to avoid confusion.

After this, I think it will be superior to the Cinnamon extension below - mainly thanks to hourly forecasts for the current day.
https://cinnamon-spices.linuxmint.com/applets/view/17
![workspace 1_2018-03-29-22 20 24](https://user-images.githubusercontent.com/6375934/38109302-61768882-33a0-11e8-8c79-85335b3cc01c.jpg)

**Comment by Sadi58** [comment]
Thanks for including this in the future plans.
Meanwhile, after enabling the Cinnamon appindicator support, I now see that actually displaying location name in tooltip (issue 84) might be more useful than including it in the menu as I first suggested above.

**Comment by bitseater** [comment]
The Ubuntu AppIndicator used by Meteo is too restricted. I can show only a menu when click on indicator, so i have use this menu to show lines with icon and data from current weather. But i can design a new interface to show when mouse over indicator.

To know limitations to AppIndicator : [https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators](https://wiki.ubuntu.com/DesktopExperienceTeam/ApplicationIndicators)

**Comment by bitseater** [comment]
Added city label to indicator.

**Comment by Sadi58** [comment]
Thanks for the improvements, including **_city label_** in the indicator menu, but will you also include **_multi-city support_** to a future milestone?

**Comment by bitseater** [comment]
Well @Sadi58 , multicity support requires a modification of main ui. So it will wait until 1.0 release. Added to [Roadmap in wiki page](https://github.com/bitseater/weather/wiki)
