### ISSUE TITLE
dark theme in preferences has no effect

### ISSUE THREAD

**Issue by Sadi58** [bitseater/weather#83]
I think I'd prefer enabling Dark theme but toggling it on and off makes no difference under Linux Mint 18.3 Cinnamon.
It's not a big deal but perhaps it could be included at the bottom of the to-do list ;-)
(I'm just trying to show my appreciation for this valuable work by trying to contribute to its perfection)
![istanbul marmara region tr_2018-03-30-13 31 33](https://user-images.githubusercontent.com/6375934/38135097-ee61ed6c-341e-11e8-8aaa-cf2bcff7e5d2.jpg)

**Comment by bitseater** [comment]
Well, this is a issue related to Cinnamon, not to Meteo. Cinnamon melt gtk2 and gtk3 features, so you must have installed a gtk theme with dark version both in gtk2 and gtk3. Also you can enabled this possibility in Preferences. can i leave an opinion? install gnome :P
