### ISSUE TITLE
[Feature Request] showing location in systray tooltip

### ISSUE THREAD

**Issue by Sadi58** [bitseater/weather#84]
Currently, on mouse hover the generic app name shows in tooltip as seen below.
But I think it would be more useful if we could see the location name instead (especially in view of possible multi-location support in the next release)
![workspace 1_2018-03-30-13 22 34](https://user-images.githubusercontent.com/6375934/38135397-8665a74c-3420-11e8-90ef-517ade43039d.jpg)

**Comment by bitseater** [comment]
This tooltip is from cinnamon. AppIndicator don't have tooltip. For best support to AppIndicator in Cinnamon i suggest you to try [Systray indicator to Cinnamon](https://github.com/lestcape/Systray-Indicator)
