### ISSUE TITLE
[Feature Request] Show Meteo on first click

### ISSUE THREAD

**Issue by Sadi58** [bitseater/weather#85]
Currently, when we click on the systray icon we get roughly the left half of the window that is displayed after clicking **Show Meteo** at the bottom.
I think if would be better to have that main window displayed on the first click (something like the screenshot included in issue 82)
We already see a brief display of current weather in the systray, and we would often want to see  weather forecast for the coming hours and/or days when we click on it.

**Comment by bitseater** [comment]
This feature is not supported by AppIndicator. Sorry.
