### ISSUE TITLE
[Feature Request] Metric system wind speed

### ISSUE THREAD

**Issue by Sadi58** [bitseater/weather#87]
I think it would be more useful to use **kilometers per hour (kph)** instead of meters per hour in the metric system.
( _PS: I think that's all from me - no more issues or feature requests that I can think of_  ; -)

**Comment by bitseater** [comment]
Well, it's seems more logical to the range of velocities.

**Comment by bitseater** [comment]
Fixed with [6e06985](https://github.com/bitseater/weather/commit/6e0698587b2685da710cc769c404de0798319971)

**Comment by Sadi58** [comment]
A quick note that the previous "m/s" remains in Preferences menu dropdown options - only "on paper" though ;-)

**Comment by bitseater** [comment]
Uuuuupsssss

**Comment by bitseater** [comment]
Fixed with [809a695](https://github.com/bitseater/weather/commit/809a695e3bb4cde788a80b0e3752f1a887ab2d5e)
