### ISSUE TITLE
zoom level consistency

### ISSUE THREAD

**Issue by SimoSirel** [bitseater/weather#96]
In Maps(Dark Sky) mode after changing between info Tabs(Temp, clouds, ...) zoom level info is lost. Works correctly in OpenWeatherMap mode. Zooming level should also be consistent between modes.

**Comment by bitseater** [comment]
Hi @SimoSirel . For Dark Sky mode , the program uses embed maps with a limited (but free) API. To a better and enhanced performance, it's needed a billing account.
