### ISSUE TITLE
Can't launch app after update

### ISSUE THREAD

**Issue by giovannicaligaris** [bitseater/weather#97]
After the new update 0.8.2 now I can't launch the app at all. Even if I try to do it from terminal nothing shows up. It just hangs there without any results.

**Comment by bitseater** [comment]
Hi @giovannicaligaris . Sorry for the inconvenience. I have forgotten to maximize window on start to change API key. Now it's fixed. You can download new deb package at  [Release page](https://github.com/bitseater/weather/releases/tag/0.8.3), or wait to new flatpak/snap package which will build in a few hours. It will be available at PPA in a few minutes.

**Comment by bitseater** [comment]
Fixed with [0129fc4](https://github.com/bitseater/weather/commit/0129fc495d00904293dab3bc722a002d94d48157)
